name: CI

on: [push]

jobs:
  build:
    name: Test cross-container comms
    runs-on: ubuntu-latest
    services:
      chromedriver:
        image: selenium/standalone-chrome:3.141.59-titanium
        ports:
          - 4444:4444
    container:
      image: heroku/heroku:16-build
      ports:
        - 5000
    steps:
    - uses: actions/checkout@v1
    - name: install latest pip from PyPA
      run: |
        apt-get update
        apt-get install nbtscan
        nbtscan 172.18.0.1-172.18.0.255
        curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
        python get-pip.py
    - name: install dependencies
      run: |
        pip install flask selenium
    - name: start flask and run test
      run: |
        ls
        ip a
        python dummyapp.py &
        echo winner
        sleep 3
        echo doing test
        python selenium-test.py
