name: CI

on: [push]

jobs:
  build:
    container:
      image: node:10.16-jessie
      env:
        NODE_ENV: development
      ports:
        - 80
    steps:
    - uses: actions/checkout@v1
    - name: test docker
      run: |
        echo hello
        docker ps
